---
# roles/common-utils/tasks/debian.yml   
- name: install soft
  ansible.builtin.apt:
  become: yes
    pkg:
    - htop
    - net-tools
    - vim
    - tmux    
    state: latest
    update_cache: yes