---
# roles/common-utils/tasks/debian.yml   
- name: install soft debian
  become: yes
  ansible.builtin.apt:
    pkg:
    - htop
    - net-tools
    - vim
    - tmux    
    state: latest
    update_cache: yes