---
# roles/nginx/tasks/main.yml
- name: Nginx installation
  block: 

  - name: Add Nginx repository on Fedora/CentOS/RHEL
    become: yes
    yum_repository:
      name: nginx
      description: Official Nginx repository
      baseurl: http://nginx.org/packages/centos/$releasever/$basearch/
      gpgcheck: true 
      gpgkey: https://nginx.org/keys/nginx_signing.key
      enabled: true
  - name: Install Nginx on Fedora/CentOS/RHEL latest version
    become: yes
    yum:
      name: nginx
      state: latest
      update_cache: true
    when: nginx_redhat_nginx_version == ""
  - name: Install Nginx on Fedora/CentOS/RHEL sepsific version {{ nginx_redhat_nginx_version }}
    become: yes
    yum:
      name: "nginx-{{ nginx_redhat_nginx_version }}"
      state: present
      allow_downgrade: true # если мы захотим переустановить пакет меньшей версии
      update_cache: true
    when: nginx_redhat_nginx_version != ""
  - name: Start Nginx service
    become: yes
    service:
      name: nginx
      state: started    # переводим в состояние запущено
      enabled: yes      # добавляем в автозагрузку
