---
- hosts: web_servers
  vars_files:
    - nginx.vault  
  vars: 
    - auth_basic_user_file: "/etc/nginx/.htpasswd"
  gather_facts: yes
  roles:
    - role: nginx
    - role: install-soft    
    - role: rebrain-web-std